[1,"Error occurred during cleanup: Error: El proceso no tiene acceso al archivo porque est√° siendo utilizado por otro proceso. (os error 32): remove 'C:\\Users\\dig91\\AppData\\Local\\Temp\\quarto-session52a51304185bfd93'\n"]
